name: Update docs/docs/index.md

on:
  push:
    branches:
      - master

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:z
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate docs/docs/index.md
      run: |
        echo "Generating docs/docs/index.md..."
        cat README.md > docs/docs/index.md

    - name: Commit changes
      run: |
        git add docs/docs/index.md
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Update docs/docs/index.md"
          git push
        else
          echo "No changes to commit"
        fi
