name: Update docs/docs/index.md
on: push
permissions:
  pull-requests: write
  contents: write 
  repository-projects: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.name "Anselm Kiefner"
          git config --global user.email "fuzzylogic-github@anselm.kiefner.de"
      - name: Update docs/docs/index.md
        run: |
          echo "Generating docs/docs/index.md..."
          cat README.md > docs/docs/index.md
      - name: Commit and push changes
        run: |
          git add docs/docs/index.md
          git commit -m "Update docs/docs/index.md"
          git push
